### ISSUE TITLE
Inputs with type attribute throw an exception when affixed in IE8

### ISSUE THREAD

**Issue by Hyzual** [searls/jasmine-fixture#33]
Hi,
I can't seem to affix inputs with type attributes on IE8. 
```javascript
affix('input[type="checkbox"]'); // Throws TypeError: Object doesn't support this property or method
```
It also throws an error with `type="hidden"` and maybe other types as well.

I think it is due to a known problem in jQuery with IE8 :
http://bugs.jquery.com/ticket/8232

I don't know whether it can be fixed in jasmine-fixture, I just thought I'd report it anyway to save others some time.
I fixed it in my test by using jQuery's `append()` instead of `affix()` : 

```javascript
var $someClass = affix('.someClass');
$someClass.append('<input type="checkbox" />');
```

**Comment by searls** [comment]
Closing until we can reproduce w/ emmet
