### ISSUE TITLE
Namespace collision with Bootstrap's JS

### ISSUE THREAD

**Issue by rspeicher** [searls/jasmine-fixture#43]
The Javascript library for Twitter's Bootstrap [defines an `affix` method](http://getbootstrap.com/javascript/#js-overview), and while testing something that used it I ran into errors in jasmine-fixture because of it.

The code using Bootstrap's affix might look something like this:

``` coffee
$('.issuable-affix').affix offset:
  top: -> @top = ($('.issuable-affix').offset().top - 70)
  bottom: -> @bottom = $('.footer').outerHeight(true)
```

And when running a spec using jasmine-fixture, we get the error: `TypeError: selectorOptions.split is not a function`

I don't have a solution to propose at the moment.

**Comment by searls** [comment]
Ugh. Me neither.
