### ISSUE TITLE
Incorrect value set on input field.

### ISSUE THREAD

**Issue by marosluuce** [searls/jasmine-fixture#44]
I tried this: `affix('input[type="user@example.com"]');`

I got `$('input').val() == 'user.com'`.

Tried tracking the issue down, but the html generation code seemed kinda impenetrable. I've got a workaround in my tests. Any thoughts on how to fix this for real?

**Comment by searls** [comment]
1. The HTML generation code is just about literally impenetrable. I'm honestly surprised we haven't run into this one before. In the past, any workarounds we've needed to add have been to the crazy regex side. 

2. No off-hand thoughts on how to fix this, but I'd really appreciate if you pulled down the project and at least wrote a failing test and took a few minutes of head-scratching at it.

**Comment by marosluuce** [comment]
Yeah, I added a test but quickly gave up trying to fix it. Might take another look this weekend.

**Comment by searls** [comment]
hey @marosluuce you may want to check jasmine-fixture@2. i suspect this works now
