### ISSUE TITLE
Cannot affix tags with dashes in their name (e.g. Angular directives)

### ISSUE THREAD

**Issue by Hyzual** [searls/jasmine-fixture#47]
Hi !
Thanks again for this library, it is very useful.

Lately I wanted to use it to unit-test some AngularJS code that made use of directives. One of my directives is an element named `<backlog-item>`. I would like to simply affix it. I don't want to use `$compile` because I just want to verify that traversing to this element with a bit of jQuery works.

I found out that I don't seem to be able to affix tags that contain dashes in their names : `affix("backlog-item");` actually affixes a `<backlog>` tag.

Here is a plunker to show this situation : http://plnkr.co/edit/TSvf1H?p=preview

I hope something can be done, otherwise I have found a workaround by using `$('<backlog-item').appendTo('body');`

**Comment by searls** [comment]
Thanks for the issue. All I can say off-the-cuff is that jasmine-fixture/zencoding were written well before dasherized element names for web components became a Thing™.

Would you mind adding a failing test and posting it as a PR?

**Comment by Hyzual** [comment]
Thanks for the quick fix :) I'll be sure to try the new major version
