### ISSUE TITLE
Adding default text inside of element

### ISSUE THREAD

**Issue by aleksandarcrvc** [searls/jasmine-fixture#51]
I just have to say that this is not issue but it can be cool improvement for this library.

Current implementation doesn't allow us to inject default text inside of element. That functionality will provide better flexibility for developers. It can be easy used to add {{}} for mustache rendering etc.

Example

I need a div.sample-id with content {{variable}}. In order to affix that I have to:

affix('div.sample-id').text('{{variable}}')

It would be really handy if we have something like

affix('div.sample-id{any-text}') where {} will be parsed as text for element.

**Comment by searls** [comment]
This already works:

```
affix('span{hello there}')
```

Will affix `<span>hello there</span>`.

It's covered with this unit test:

```
    context "text node with space char", ->
      Given -> affix('a.link{Text With Space}')
      Then -> expect($('.link').text()).toEqual('Text With Space')
```

**Comment by aleksandarcrvc** [comment]
This doesn't work in this scenario. I want to put following text as text of span element:
{{text}}
By documentation if should be:
affix('span{{{text}}}')
