### ISSUE TITLE
Calling affix with an object causes it to be escaped

### ISSUE THREAD

**Issue by nrodriguez** [searls/jasmine-fixture#52]
I have an object:

```
var mockParams = {"object":"some-object-uuid"}
```

and I call affix with it

```
htmlDom = affix('a[data-xo-love="true"][data-params=' + JSON.stringify(mockParams) + ']')
```

causes the resulting dom to be

```
<a data-xo-love="true" data-params="{" object":"some-object-uuid"}"=""></a>
```

**Comment by searls** [comment]
Can this issue be simplified? Is it simply that the selector doesn't escape `"` characters? If you escape the stringified output yourself does it work?

**Comment by nrodriguez** [comment]
I was able to resolve the issue by replacing quotes with their HTML entity version..

`JSON.stringify(mockParams).replace(/"/g, '&quot;')`

seems to allows the affix to properly create the html elements

**Comment by searls** [comment]
sounds good enough for me!
