### ISSUE TITLE
Data attributes are being converted to all lowercase 

### ISSUE THREAD

**Issue by stephen-puiszis** [searls/jasmine-fixture#54]
Hey Justin,

I came across some unexpected behavior using `2.0.0`. When using `affix()` with data attributes, each key string is being downcased. I was expecting that any data attribute key that I passed in would not be altered. My use case was needing data attributes with camel-case keys (whether or not that's a good idea or not is certainly debatable).

I'm not sure this is actually worth fixing since there are some pretty easy workarounds, like directly setting the data attribute on the object via jQuery, but I wanted to submit this in case someone else comes across it. 

Spec: 
```coffeescript
# uploader_spec.js.coffee

describe "Uploader", ->
  beforeEach ->
    @config =
      s3BucketEndpoint: "s3.amazon.com",
      s3AccessKey: "s3-access-key",
      s3Subdirectory: "test-dir",
  
    data = ""
    for key, value of @config
      data += "data-#{key}='#{value}' "

    affix(".js--uploader[#{data}]"
```

Console: 

```javascript 
$(".js--audioUploader").data("s3BucketEndpoint")
undefined

$(".js--audioUploader").data("s3bucketendpoint")
"s3.amazon.com"
```

**Comment by searls** [comment]
jQuery camelCases data attributes only by converting it from dash-erized format between each token, it does not take case into account.  In this case you want your keys to be `s3-bucket-endpoint` and so forth in order for jQuery to pick them up.

**Comment by stephen-puiszis** [comment]
@searls thank you.
