### ISSUE TITLE
Fixtures are not always removed from the dom

### ISSUE THREAD

**Issue by zacharyw** [searls/jasmine-fixture#56]
I have fixture like so:

```
beforeEach(function(){
  affix('body');
});
```

I then run some code that adds a couple of classes to the body. In this case it's a bootstrap modal opening, which adds `.modal-open` and another custom class.

I have another spec which expects this class to *not* be there. If it runs after the spec that adds the class, it fails because the class is still present from the previous spec.

If I had a `$('body').removeClass('modal-open')` to the end of the spec that adds it, everything works.

**Comment by searls** [comment]
Since every DOM will always have a `body`, it can't be cleaned up safely by the library, so I'd strongly encourage you to find a container on the DOM that you do own (if `body` is hardcoded in the production source, you may just need to refactor it to take an argument)

**Comment by zacharyw** [comment]
@searls Ah, thank you for the quick explanation. Unfortunately for this particular iOS bug that I'm trying to workaround (https://bugs.webkit.org/show_bug.cgi?id=176896), I have to use the body.

It's a rare occurrence so hopefully won't be an issue with most tests.
